# Generated by Django 3.0.14 on 2023-03-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230320_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Contact',
        ),
    ]
